### ISSUE TITLE
Make RON not eliminate

### ISSUE THREAD

**Issue by jb567** [zhantongz/stvCount#1]
make it so that a RON candidate is never eliminated from the ballot for Return to nomination phase, and if RON wins a seat mark the other 'winners' as RON

**Comment by zhantongz** [comment]
what?

**Comment by zhantongz** [comment]
Oh, Re-Open Nominations is not a supported preference in Model Canadian elections although voters may decline a ballot. But if MHoC requests it, I can modify the program.

**Comment by zhantongz** [comment]
RON candidate is now supported by configuring `ron` option.
